CMDBuddyFinal/Controllers/CFerramentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMDBuddyFinal.Models;
using MySql.Data.MySqlClient;

namespace CMDBuddyFinal.Controllers
{
    public class CFerramentasController : Controller
    {
        // GET: CFerramentas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CalHoras()
        {
            ViewBag.Message = "Calculadora de Horas";
            return View();
        }

        public ActionResult RelICAO()
        {
            ViewBag.Message = "Relação de ICAO";
            return View();
        }

        public ActionResult ConMedidas()
        {
            ViewBag.Message = "Conversor de Medidas";
            return View();
        }

        [HttpPost]
        public ActionResult CalculaHoras(HVoo tempo)
        {
            var horasDecimal = (decimal)tempo.Horas + (decimal)tempo.Minutos / 60 + (decimal)tempo.Segundos / 3600;
            ViewBag.Resultado = horasDecimal.ToString("F2");
            return View("CalHoras", tempo);
        }
        [HttpPost]
        public ActionResult Converte(CMedida medida)
        {
            switch (medida.opcaoConversao)
            {
                case "kilo":
                    var kilo = medida.valor * 2.205;
                    ViewBag.Resultado = $"{medida.valor:F2} kg = {kilo:F2} lb";
                    break;
                case "metro":
                    var metro = medida.valor / 1609.344;
                    ViewBag.Resultado = $"{medida.valor:F2} m = {metro:F2} mi";
                    break;
                case "litro":
                    var litro = medida.valor / 3.785;
                    ViewBag.Resultado = $"{medida.valor:F2} L = {litro:F2} gal";
                    break;
                case "centimetro":
                    var centimetro = medida.valor / 2.54;
                    ViewBag.Resultado = $"{medida.valor:F2} cm = {centimetro:F2} in";
                    break;
                default:
                    ViewBag.Resultado = "Opção inválida.";
                    break;
            }

            return View("ConMedidas", medida);
        }
        List<DBordo> lstDiario = new List<DBordo>();

        [HttpPost]
        public ActionResult PesquisaICAO(PICAO picao)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT aerodromo FROM TabICAO WHERE ";
            StrQuery += "icao = '" + picao.ICAO + "';";
            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                if (dr.HasRows)
                {
                    _ = dr.Read();
                    ViewBag.Aerodromo = dr.GetString(0);
                    return View("RelICAO", picao);
                }
                else
                {
                    ViewBag.Aerodromo = "Não Encontrado";
                    return View("RelICAO", picao);
                }
            }
        }
        [HttpPost]
        public ActionResult PesquisaAerodromo(PICAO picao)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT icao FROM TabICAO WHERE ";
            StrQuery += "aerodromo = '" + picao.Aerodromo + "';";
            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                if (dr.HasRows)
                {
                    _ = dr.Read();
                    ViewBag.ICAO = dr.GetString(0);
                    return View("RelICAO", picao);
                }
                else
                {
                    ViewBag.ICAO = "Não Encontrado";
                    return View("RelICAO", picao);
                }
            }
        }
    }
}

CMDBuddyFinal/Views/CFerramentas/CalHoras.cshtml
@model CMDBuddyFinal.Models.HVoo

@{
    ViewBag.Title = "CalHoras";
    Layout = "~/Views/Shared/_LayoutPiloto.cshtml";
}
<br />
<br />
<h2>Calculadora de Horas</h2>

<body style="background-color: #b1ccc4;">
    @using (Html.BeginForm("CalculaHoras", "CFerramentas", FormMethod.Post))
    {
        <div class="form-group">
            <label>Horas:</label>
            @Html.TextBoxFor(model => model.Horas, new { @class = "form-control" })
            <label>Minutos:</label>
            @Html.TextBoxFor(model => model.Minutos, new { @class = "form-control" })
            <label>Segundos:</label>
            @Html.TextBoxFor(model => model.Segundos, new { @class = "form-control" })
        </div>

        <button type="submit" class="btn btn-primary">Converter</button>
    }

    @if (ViewBag.Resultado != null)
    {
        <br>
        <div class="alert alert-info">O tempo de voo total é de @ViewBag.Resultado horas.</div>
    }
</body>

CMDBuddyFinal/Views/CFerramentas/ConMedidas.cshtml
@model CMDBuddyFinal.Models.CMedida

@{
    ViewBag.Title = "Conversor de medidas";
    Layout = "~/Views/Shared/_LayoutPiloto.cshtml";
}
<br />
<br />
<h2>Conversor de medidas</h2>

<body style="background-color: #b1ccc4;">

    @using (Html.BeginForm("Converte", "CFerramentas", FormMethod.Post))
    {
        <div class="form-group">
            <label for="medida">Selecione a medida que deseja converter:</label>
            <select class="form-control" id="medida" name="opcaoConversao">
                <option value="kilo">Kilograma (kg) para Libra (lb)</option>
                <option value="metro">Metro (m) para Milha (mi)</option>
                <option value="centimetro">Centímetro (cm) para Polegada (in)</option>
                <option value="litro">Litro (L) para Galão (gal)</option>
            </select>
        </div>
        <div class="form-group">
            <label for="valor">Insira o valor a ser convertido:</label>
            <br />
            @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control col-4" } })
        </div>
        <button type="submit" class="btn btn-primary">Converter</button>
        if (ViewBag.Resultado != null)
        {
            <hr>
            <div class="alert alert-info">@ViewBag.Resultado</div>
        }
    }

</body>

CMDBuddyFinal/Views/CFerramentas/Index.cshtml
@{
    ViewBag.Title = "Caixa de Ferramentas";
    Layout = "~/Views/Shared/_LayoutPiloto.cshtml";
}


<br>
<br>
<body class="d-flex h-100 text-center text-bg-dark" style="background-image: url('https://bg-so-1.zippyimage.com/2023/04/22/d6daf08bc25ff35f4072a600e690a76b.png'); ">
    <main class="px-3">
        <br />
        <br />
        <h1>Caixa de Ferramentas</h1>
        <br />
        <br />
        <p class="lead">
            @Html.ActionLink("Calculadora de Horas", "CalHoras", "CFerramentas", null, new { @class = "btn btn-primary" })
            @Html.ActionLink("Relação de códigos ICAO", "RelICAO", "CFerramentas", null, new { @class = "btn btn-primary" })
            @Html.ActionLink("Conversor de Medidas", "ConMedidas", "CFerramentas", null, new { @class = "btn btn-primary" })
        </p>
    </main>
</body>

CMDBuddyFinal/Views/CFerramentas/RelICAO.cshtml
@model CMDBuddyFinal.Models.PICAO

@{
    ViewBag.Title = "RelICAO";
    Layout = "~/Views/Shared/_LayoutPiloto.cshtml";
}
<br />
<br />
<h2>Relação de códigos ICAO</h2>


<body style="background-color: #b1ccc4;">
    @using (Html.BeginForm("PesquisaICAO", "CFerramentas", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ICAO, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.ICAO, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-primary">Pesquisar</button>
    }

    @using (Html.BeginForm("PesquisaAerodromo", "CFerramentas", FormMethod.Post))
    {

        <div class="form-group">
            @Html.LabelFor(model => model.Aerodromo, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.Aerodromo, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-primary">Pesquisar</button>
    }


    @if (ViewBag.Aerodromo != null)
    {
        <br>
        <div class="alert alert-info">@Model.ICAO = @ViewBag.Aerodromo.</div>
    }
    @if (ViewBag.ICAO != null)
    {
        <br>
        <div class="alert alert-info">@Model.Aerodromo = @ViewBag.ICAO .</div>
    }

</body>