CMDBuddyFinal/Models/DBordo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace CMDBuddyFinal.Models
{
    public class DBordo
    {
        public int IdBordo { get; set; }
        [Display(Name = "Número de Tripulantes")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public int NumeroTripulantes { get; set; }
        [Display(Name = "Nome dos Tripulantes")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string NomeTripulantes { get; set; }
        [Display(Name = "Horário")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string Hora { get; set; }
        [Display(Name = "Marca do Avião")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string Marca { get; set; }
        [Display(Name = "Fabricante do Avião")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string Fabricante { get; set; }
        [Display(Name = "Modelo do Avião")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string Modelo { get; set; }
        [Display(Name = "Número de Série")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string NS { get; set; }
        [Display(Name = "Categoria Registrada")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string CatReg { get; set; }
        [Display(Name = "Horas da Célula Anterior")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public float HoraCelAnt { get; set; }
        [Display(Name = "Horas Totais da Página na Célula")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public float HoraCelPag { get; set; }
        [Display(Name = "Total Horas pela Célula")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public float TotHoraCel { get; set; }
        [Display(Name = "Aeródromo de Origem")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string Origem { get; set; }
        [Display(Name = "Aeródromo de Destino")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string Destino { get; set; }
        [Display(Name = "Horário de Partida")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorPart { get; set; }
        [Display(Name = "Horário de Decolagem")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorDecolagem { get; set; }
        [Display(Name = "Horário de Pouso")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorPouso { get; set; }
        [Display(Name = "Horas Corrigidas")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorCor { get; set; }
        [Display(Name = "Horas Diurnas")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorDiurno { get; set; }
        [Display(Name = "Horas Noturnas")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorNoturno { get; set; }
        [Display(Name = "Horas com IFRR")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorIFRR { get; set; }
        [Display(Name = "Horas com IFRC")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorIFRC { get; set; }
        [Display(Name = "Horas Totais")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string HorTotal { get; set; }
        [Display(Name = "Combustíveis Totais")]
        [Required(ErrorMessage = "Por favor, preencha este campo")]
        public string CombustTotal { get; set; }
        [Display(Name = "Ocorrências")]
        public string Ocorrencias { get; set; }
    }
}

CMDBuddyFinal/Controllers/DBordoController.cs
using CMDBuddyFinal.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMDBuddyFinal.Controllers
{
    public class DBordoController : Controller
    {
        // GET: DBordo
        List<DBordo> lstDiario = new List<DBordo>();
        
        public ActionResult Index()
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT * FROM bordo ORDER BY idBordo";
            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                while (dr.Read())
                {
                    DBordo diario = new DBordo()
                    {
                        IdBordo = Convert.ToInt32(dr["idBordo"]),
                        NumeroTripulantes = Convert.ToInt32(dr["NumeroTripulantes"]),
                        NomeTripulantes = Convert.ToString(dr["NomeTripulantes"]),
                        Hora = Convert.ToString(dr["Hora"]),
                        Marca = Convert.ToString(dr["Marca"]),
                        Fabricante = Convert.ToString(dr["Fabricante"]),
                        Modelo = Convert.ToString(dr["Modelo"]),
                        NS = Convert.ToString(dr["NS"]),
                        CatReg = Convert.ToString(dr["CatReg"]),
                        HoraCelAnt = Convert.ToSingle(dr["HorCelAnt"]),
                        HoraCelPag = Convert.ToSingle(dr["HorCelDia"]),
                        TotHoraCel = Convert.ToSingle(dr["ValHorCel"]),
                        Origem = Convert.ToString(dr["Origem"]),
                        Destino = Convert.ToString(dr["Destino"]),
                        HorPart = Convert.ToString(dr["HorPart"]),
                        HorDecolagem = Convert.ToString(dr["HorDec"]),
                        HorPouso = Convert.ToString(dr["HorPou"]),
                        HorCor = Convert.ToString(dr["HorCor"]),
                        HorDiurno = Convert.ToString(dr["HorDiu"]),
                        HorNoturno = Convert.ToString(dr["HorNotu"]),
                        HorIFRR = Convert.ToString(dr["HorIFRR"]),
                        HorIFRC = Convert.ToString(dr["HorIFRC"]),
                        HorTotal = Convert.ToString(dr["HorTotal"]),
                        CombustTotal = Convert.ToString(dr["CombTotal"]),
                        Ocorrencias = Convert.ToString(dr["Ocorr"])

                    };
                    lstDiario.Add(diario);
                }
            }
            return View(lstDiario);
        }
        
        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Salvar(DBordo dbordo)
        {
            using (Conexao conexao = new Conexao())
            {
                string StrQuery = "insert into bordo(NumeroTripulantes, NomeTripulantes, Hora, Marca, Fabricante, Modelo, NS, CatReg, HorCelAnt, HorCelDia, ValHorCel, Origem, Destino, HorPart, HorDec, HorPou, HorCor, HorDiu, HorNotu, HorIFRR, HorIFRC, HorTotal, CombTotal, Ocorr) values(";
                StrQuery += "'" + dbordo.NumeroTripulantes + "',";
                StrQuery += "'" + dbordo.NomeTripulantes + "',";
                StrQuery += "'" + dbordo.Hora + "',";
                StrQuery += "'" + dbordo.Marca + "',";
                StrQuery += "'" + dbordo.Fabricante + "',";
                StrQuery += "'" + dbordo.Modelo + "',";
                StrQuery += "'" + dbordo.NS + "',";
                StrQuery += "'" + dbordo.CatReg + "',";
                StrQuery += "'" + dbordo.HoraCelAnt + "',";
                StrQuery += "'" + dbordo.HoraCelPag + "',";
                StrQuery += "'" + dbordo.TotHoraCel + "',";
                StrQuery += "'" + dbordo.Origem + "',";
                StrQuery += "'" + dbordo.Destino + "',";
                StrQuery += "'" + dbordo.HorPart + "',";
                StrQuery += "'" + dbordo.HorDecolagem + "',";
                StrQuery += "'" + dbordo.HorPouso + "',";
                StrQuery += "'" + dbordo.HorCor + "',";
                StrQuery += "'" + dbordo.HorDiurno + "',";
                StrQuery += "'" + dbordo.HorNoturno + "',";
                StrQuery += "'" + dbordo.HorIFRR + "',";
                StrQuery += "'" + dbordo.HorIFRC + "',";
                StrQuery += "'" + dbordo.HorTotal + "',";
                StrQuery += "'" + dbordo.CombustTotal + "',";
                StrQuery += "'" + dbordo.Ocorrencias + "');";
                using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
                {
                    comando.ExecuteNonQuery();
                }
                return RedirectToAction("Index");
            }
        }
        
        public ActionResult Editar(int Id)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT * FROM bordo WHERE ";
            StrQuery += "idBordo = " + Id + ";";

            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                if (dr.HasRows)
                {
                    dr.Read();
                    DBordo dbordo = new DBordo();
                    dbordo.IdBordo = Convert.ToInt32(dr["idBordo"]);
                    dbordo.NumeroTripulantes = Convert.ToInt32(dr["NumeroTripulantes"]);
                    dbordo.NomeTripulantes = Convert.ToString(dr["NomeTripulantes"]);
                    dbordo.Hora = Convert.ToString(dr["Hora"]);
                    dbordo.Marca = Convert.ToString(dr["Marca"]);
                    dbordo.Fabricante = Convert.ToString(dr["Fabricante"]);
                    dbordo.Modelo = Convert.ToString(dr["Modelo"]);
                    dbordo.NS = Convert.ToString(dr["NS"]);
                    dbordo.CatReg = Convert.ToString(dr["CatReg"]);
                    dbordo.HoraCelAnt = Convert.ToSingle(dr["HorCelAnt"]);
                    dbordo.HoraCelPag = Convert.ToSingle(dr["HorCelDia"]);
                    dbordo.TotHoraCel = Convert.ToSingle(dr["ValHorCel"]);
                    dbordo.Origem = Convert.ToString(dr["Origem"]);
                    dbordo.Destino = Convert.ToString(dr["Destino"]);
                    dbordo.HorPart = Convert.ToString(dr["HorPart"]);
                    dbordo.HorDecolagem = Convert.ToString(dr["HorDec"]);
                    dbordo.HorPouso = Convert.ToString(dr["HorPou"]);
                    dbordo.HorCor = Convert.ToString(dr["HorCor"]);
                    dbordo.HorDiurno = Convert.ToString(dr["HorDiu"]);
                    dbordo.HorNoturno = Convert.ToString(dr["HorNotu"]);
                    dbordo.HorIFRR = Convert.ToString(dr["HorIFRR"]);
                    dbordo.HorIFRC = Convert.ToString(dr["HorIFRC"]);
                    dbordo.HorTotal = Convert.ToString(dr["HorTotal"]);
                    dbordo.CombustTotal = Convert.ToString(dr["CombTotal"]);
                    dbordo.Ocorrencias = Convert.ToString(dr["Ocorr"]);

                    return View(dbordo);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
        [HttpPost]
        public ActionResult Editar(DBordo dbordo)
        {
            using (Conexao conexao = new Conexao())
            {
                string StrQuery = "update bordo set ";
                StrQuery += "NumeroTripulantes = " + dbordo.NumeroTripulantes + ", ";
                StrQuery += "NomeTripulantes = '" + dbordo.NomeTripulantes + "', ";
                StrQuery += "Marca = '" + dbordo.Marca + "', ";
                StrQuery += "Fabricante = '" + dbordo.Fabricante + "', ";
                StrQuery += "Modelo = '" + dbordo.Modelo + "', ";
                StrQuery += "NS = '" + dbordo.NS + "', ";
                StrQuery += "CatReg = '" + dbordo.CatReg + "', ";
                StrQuery += "HorCelAnt = " + dbordo.HoraCelAnt + ", ";
                StrQuery += "HorCelDia = " + dbordo.HoraCelPag + ", ";
                StrQuery += "ValHorCel = " + dbordo.TotHoraCel + ", ";
                StrQuery += "Origem = '" + dbordo.Origem + "', ";
                StrQuery += "Destino = '" + dbordo.Destino + "', ";
                StrQuery += "HorPart = '" + dbordo.HorPart + "', ";
                StrQuery += "HorDec = '" + dbordo.HorDecolagem + "', ";
                StrQuery += "HorPou = '" + dbordo.HorPouso + "', ";
                StrQuery += "HorCor = '" + dbordo.HorCor + "', ";
                StrQuery += "HorDiu = '" + dbordo.HorDiurno + "', ";
                StrQuery += "HorNotu = '" + dbordo.HorNoturno + "', ";
                StrQuery += "HorIFRR = '" + dbordo.HorIFRR + "', ";
                StrQuery += "HorIFRC = '" + dbordo.HorIFRC + "', ";
                StrQuery += "HorTotal = '" + dbordo.HorTotal + "', ";
                StrQuery += "CombTotal = '" + dbordo.CombustTotal + "', ";
                StrQuery += "Ocorr = '" + dbordo.Ocorrencias + "', ";
                StrQuery += "Hora = '" + dbordo.Hora + "' ";
                StrQuery += "where idBordo = " + dbordo.IdBordo + ";";
                using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
                {
                    comando.ExecuteNonQuery();
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "Select * from bordo where";
            StrQuery += " idBordo =" + Id + ";";

            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dt = comando.ExecuteReader();
                if (dt.HasRows)
                {
                    dt.Read();

CMDBuddyFinal/Views/DBordo/Delete.cshtml
@model CMDBuddyFinal.Models.DBordo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutSemNavbar.cshtml";
}
<br />
<div class="text-center">
    <h3>Excluir o Diário de Bordo?</h3>
</div>

<body style="background-color: #b1ccc4;">
    <div>
        @using (Html.BeginForm("Deletar", "DBordo", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.IdBordo)
            <div class="row">
                <div class="col-md-offset-2 col-md-18">
                    <input type="submit" value="Sim" class="btn btn-danger" /> || @Html.ActionLink("Não", "Index")
                </div>
            </div>
        }
    </div>

</body>

CMDBuddyFinal/Views/DBordo/Editar.cshtml
@model CMDBuddyFinal.Models.DBordo

@{
    ViewBag.Title = "Editar Diario de Bordo";
    Layout = "~/Views/Shared/_LayoutSemNavbar.cshtml";
}
<br />
<div class="text-center">
    <h2>Editar Diário de Bordo</h2>
</div>

<body style="background-color: #b1ccc4;">
    @using (Html.BeginForm("Editar", "DBordo", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.IdBordo)
            <div class="row">
                <div class="col-md-2">
                    @Html.LabelFor(model => model.Hora, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.Hora, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.Hora, "*Campo Obrigatório", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.NumeroTripulantes, htmlAttributes: new { @class = "control-label col-15" })
                    @Html.EditorFor(model => model.NumeroTripulantes, new { htmlAttributes = new { @class = "form-control col-15" } })
                    @Html.ValidationMessageFor(model => model.NumeroTripulantes, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-9">
                    @Html.LabelFor(model => model.NomeTripulantes, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.NomeTripulantes, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.NomeTripulantes, "*", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.Marca, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    @Html.LabelFor(model => model.Fabricante, htmlAttributes: new { @class = "control-label col-15" })
                    @Html.EditorFor(model => model.Fabricante, new { htmlAttributes = new { @class = "form-control col-15" } })
                    @Html.ValidationMessageFor(model => model.Fabricante, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.Modelo, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    @Html.LabelFor(model => model.CatReg, htmlAttributes: new { @class = "control-label col-15" })
                    @Html.EditorFor(model => model.CatReg, new { htmlAttributes = new { @class = "form-control col-15" } })
                    @Html.ValidationMessageFor(model => model.CatReg, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    @Html.LabelFor(model => model.NS, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.NS, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.NS, "*", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.HoraCelAnt, htmlAttributes: new { @class = "control-label col-15" })
                    @Html.EditorFor(model => model.HoraCelAnt, new { htmlAttributes = new { @class = "form-control col-15" } })
                    @Html.ValidationMessageFor(model => model.HoraCelAnt, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.HoraCelPag, htmlAttributes: new { @class = "control-label col-15" })
                    @Html.EditorFor(model => model.HoraCelPag, new { htmlAttributes = new { @class = "form-control col-15" } })
                    @Html.ValidationMessageFor(model => model.HoraCelPag, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.TotHoraCel, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.TotHoraCel, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.TotHoraCel, "*", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Origem, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.Origem, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.Origem, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Destino, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.Destino, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.Destino, "*", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorPart, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorPart, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorPart, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorDecolagem, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorDecolagem, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorDecolagem, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorPouso, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorPouso, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorPouso, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorCor, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorCor, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorCor, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorDiurno, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorDiurno, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorDiurno, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorNoturno, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorNoturno, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorNoturno, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorIFRR, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorIFRR, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorIFRR, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorIFRC, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorIFRC, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorIFRC, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    @Html.LabelFor(model => model.HorTotal, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.HorTotal, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.HorTotal, "*", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.CombustTotal, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.CombustTotal, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.CombustTotal, "*", new { @class = "text-danger" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Ocorrencias, htmlAttributes: new { @class = "control-label col-12" })
                    @Html.EditorFor(model => model.Ocorrencias, new { htmlAttributes = new { @class = "form-control col-12" } })
                    @Html.ValidationMessageFor(model => model.Ocorrencias, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-primary" /> || @Html.ActionLink("Volta para lista", "Index")
                </div>
            </div>
        </div>

    }
</body>

    <div>

    </div>

CMDBuddyFinal/Views/DBordo/Index.cshtml
@model IEnumerable<CMDBuddyFinal.Models.DBordo>

@{
    ViewBag.Title = "Diarios de Bordo";
    Layout = "~/Views/Shared/_LayoutPiloto.cshtml";
}

<br />
<div class="text-center">
    <h2>Diários de Bordo</h2>
</div>

<body style="background-color: #b1ccc4;">
    <p>
        @Html.ActionLink("Novo Diário de Bordo", "Novo", null, new { @class = "btn btn-primary" })
    </p>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NomeTripulantes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hora)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fabricante)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Modelo)
                </th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeTripulantes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fabricante)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.IdBordo }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Excluir", "Delete", new { id = item.IdBordo }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    </table>
</body>