CMDBuddyFinal/Controllers/LoginController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMDBuddyFinal.Models;
using Microsoft.Ajax.Utilities;

namespace CMDBuddy.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }



        
        public ActionResult Cadastra()
        {
            return View();
        }

        public ActionResult Lembra()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SalvarUsuario(Usuario usuario)
        {

            using (Conexao conexao = new Conexao())
            {
                string StrQuery = "insert into users (login, senha, nome, email) values ( ";
                StrQuery += "'" + usuario.Username + "',";
                StrQuery += "'" + usuario.Userpass + "',";
                StrQuery += "'" + usuario.Nome + "',";
                StrQuery += "'" + usuario.Email + "');";
                using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
                {
                    comando.ExecuteNonQuery();
                }
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Lembrar(Usuario usuario, Lembrar lembrar)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT * FROM users WHERE ";
            StrQuery += "email = '" + usuario.Email + "';";
            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                if (dr.HasRows)
                {
                    _ = dr.Read();
                    StrQuery = "insert into lembrar (nome, email) values ( ";
                    StrQuery += "'" + lembrar.Nome + "',";
                    StrQuery += "'" + dr.GetString(4) + "');";
                    //StrQuery += "'" + lembrar.Email + "');";
                    MySqlCommand comando1 = new MySqlCommand(StrQuery, conexao.conn);
                    dr.Close();
                    comando1.ExecuteNonQuery();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Lembra");
                }
            }
        }


    }
}

CMDBuddyFinal/Controllers/PVooController.cs
using CMDBuddyFinal.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace CMDBuddyFinal.Controllers
{
    public class PVooController : Controller
    {
        // GET: PVoo
        List<PVoo> lstPVoo = new List<PVoo>();

        public ActionResult Index()
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT * FROM pvoo ORDER BY idPVoo";
            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                while (dr.Read())
                {
                    PVoo pvoo = new PVoo()
                    {
                        idPVoo = Convert.ToInt32(dr["idPVoo"]),
                        Destinat = Convert.ToString(dr["Destinat"]),
                        HorApre = Convert.ToString(dr["HorApre"]),
                        Remet = Convert.ToString(dr["Remet"]),
                        Complem = Convert.ToString(dr["Complem"]),
                        Prefix = Convert.ToString(dr["Prefix"]),
                        RegraVoo = Convert.ToString(dr["RegraVoo"]),
                        TipoVoo = Convert.ToString(dr["TipoVoo"]),
                        NAvioes = Convert.ToString(dr["NAvioes"]),
                        TipoAviao = Convert.ToString(dr["TipoAviao"]),
                        CatEstTurb = Convert.ToString(dr["CatEstTurb"]),
                        EquipCap = Convert.ToString(dr["EquipCap"]),
                        AerodPart = Convert.ToString(dr["AerodPart"]),
                        Hora = Convert.ToString(dr["Hora"]),
                        VelCruz = Convert.ToString(dr["VelCruz"]),
                        NvlCruz = Convert.ToString(dr["NvlCruz"]),
                        Rota = Convert.ToString(dr["Rota"]),
                        AeroDest = Convert.ToString(dr["AeroDest"]),
                        DurTotVoo = Convert.ToString(dr["DurTotVoo"]),
                        AeroAlt = Convert.ToString(dr["AeroAlt"]),
                        AeroRes = Convert.ToString(dr["AeroRes"]),
                        OutrosDados = Convert.ToString(dr["OutrosDados"]),
                        Autonomia = Convert.ToString(dr["Autonomia"]),
                        PessBordo = Convert.ToString(dr["PessBordo"]),
                        RadEmer_U = Convert.ToBoolean(dr["RadEmer_U"]),
                        RadEmer_V = Convert.ToBoolean(dr["RadEmer_V"]),
                        RadEmer_E = Convert.ToBoolean(dr["RadEmer_E"]),
                        EquipSobrev_P = Convert.ToBoolean(dr["EquipSobrev_P"]),
                        EquipSobrev_D = Convert.ToBoolean(dr["EquipSobrev_D"]),
                        EquipSobrev_M = Convert.ToBoolean(dr["EquipSobrev_M"]),
                        EquipSobrev_J = Convert.ToBoolean(dr["EquipSobrev_J"]),
                        VestSobrev_L = Convert.ToBoolean(dr["VestSobrev_L"]),
                        VestSobrev_F = Convert.ToBoolean(dr["VestSobrev_F"]),
                        VestSobrev_U = Convert.ToBoolean(dr["VestSobrev_U"]),
                        VestSobrev_V = Convert.ToBoolean(dr["VestSobrev_V"]),
                        QuantBotes = Convert.ToString(dr["QuantBotes"]),
                        CapBotes = Convert.ToString(dr["CapBotes"]),
                        CorBotes = Convert.ToString(dr["CorBotes"]),
                        CorAviao = Convert.ToString(dr["CorAviao"]),
                        Observ = Convert.ToString(dr["Observ"]),
                        Pilot = Convert.ToString(dr["Pilot"])
                    };
                    lstPVoo.Add(pvoo);
                }
            }
            return View(lstPVoo);
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Salvar(PVoo pvoo)
        {
            using (Conexao conexao = new Conexao())
            {
                string StrQuery = "insert into pvoo(Destinat, HorApre, Remet, Complem, Prefix, RegraVoo, TipoVoo, NAvioes, TipoAviao, CatEstTurb, EquipCap, AerodPart, Hora, VelCruz, NvlCruz, Rota, AeroDest, DurTotVoo, AeroAlt, AeroRes, OutrosDados, Autonomia, PessBordo, RadEmer_U, RadEmer_V, RadEmer_E, EquipSobrev_P, EquipSobrev_D, EquipSobrev_M, EquipSobrev_J, VestSobrev_L, VestSobrev_F, VestSobrev_U, VestSobrev_V, QuantBotes, CapBotes, CorBotes, CorAviao, Observ, Pilot) values(";
                StrQuery += "'" + pvoo.Destinat + "',";
                StrQuery += "'" + pvoo.HorApre + "',";
                StrQuery += "'" + pvoo.Remet + "',";
                StrQuery += "'" + pvoo.Complem + "',";
                StrQuery += "'" + pvoo.Prefix + "',";
                StrQuery += "'" + pvoo.RegraVoo + "',";
                StrQuery += "'" + pvoo.TipoVoo + "',";
                StrQuery += "'" + pvoo.NAvioes + "',";
                StrQuery += "'" + pvoo.TipoAviao + "',";
                StrQuery += "'" + pvoo.CatEstTurb + "',";
                StrQuery += "'" + pvoo.EquipCap + "',";
                StrQuery += "'" + pvoo.AerodPart + "',";
                StrQuery += "'" + pvoo.Hora + "',";
                StrQuery += "'" + pvoo.VelCruz + "',";
                StrQuery += "'" + pvoo.NvlCruz + "',";
                StrQuery += "'" + pvoo.Rota + "',";
                StrQuery += "'" + pvoo.AeroDest + "',";
                StrQuery += "'" + pvoo.DurTotVoo + "',";
                StrQuery += "'" + pvoo.AeroAlt + "',";
                StrQuery += "'" + pvoo.AeroRes + "',";
                StrQuery += "'" + pvoo.OutrosDados + "',";
                StrQuery += "'" + pvoo.Autonomia + "',";
                StrQuery += "'" + pvoo.PessBordo + "',";
                StrQuery += "'" + pvoo.RadEmer_U + "',";
                StrQuery += "'" + pvoo.RadEmer_V + "',";
                StrQuery += "'" + pvoo.RadEmer_E + "',";
                StrQuery += "'" + pvoo.EquipSobrev_P + "',";
                StrQuery += "'" + pvoo.EquipSobrev_D + "',";
                StrQuery += "'" + pvoo.EquipSobrev_M + "',";
                StrQuery += "'" + pvoo.EquipSobrev_J + "',";
                StrQuery += "'" + pvoo.VestSobrev_L + "',";
                StrQuery += "'" + pvoo.VestSobrev_F + "',";
                StrQuery += "'" + pvoo.VestSobrev_U + "',";
                StrQuery += "'" + pvoo.VestSobrev_V + "',";
                StrQuery += "'" + pvoo.QuantBotes + "',";
                StrQuery += "'" + pvoo.CapBotes + "',";
                StrQuery += "'" + pvoo.CorBotes + "',";
                StrQuery += "'" + pvoo.CorAviao + "',";
                StrQuery += "'" + pvoo.Observ + "',";
                StrQuery += "'" + pvoo.Pilot + "');";
                using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
                {
                    comando.ExecuteNonQuery();
                }
                return RedirectToAction("Index");
            }
        }

        public ActionResult Editar(int Id)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT * FROM pvoo WHERE ";
            StrQuery += "idPVoo = " + Id + ";";

            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                if (dr.HasRows)
                {
                    dr.Read();
                    PVoo pvoo = new PVoo();
                    pvoo.idPVoo = Convert.ToInt32(dr["idPVoo"]);
                    pvoo.Destinat = Convert.ToString(dr["Destinat"]);
                    pvoo.HorApre = Convert.ToString(dr["HorApre"]);
                    pvoo.Remet = Convert.ToString(dr["Remet"]);
                    pvoo.Complem = Convert.ToString(dr["Complem"]);
                    pvoo.Prefix = Convert.ToString(dr["Prefix"]);
                    pvoo.RegraVoo = Convert.ToString(dr["RegraVoo"]);
                    pvoo.TipoVoo = Convert.ToString(dr["TipoVoo"]);
                    pvoo.NAvioes = Convert.ToString(dr["NAvioes"]);
                    pvoo.TipoAviao = Convert.ToString(dr["TipoAviao"]);
                    pvoo.CatEstTurb = Convert.ToString(dr["CatEstTurb"]);
                    pvoo.EquipCap = Convert.ToString(dr["EquipCap"]);
                    pvoo.AerodPart = Convert.ToString(dr["AerodPart"]);
                    pvoo.Hora = Convert.ToString(dr["Hora"]);
                    pvoo.VelCruz = Convert.ToString(dr["VelCruz"]);
                    pvoo.NvlCruz = Convert.ToString(dr["NvlCruz"]);
                    pvoo.Rota = Convert.ToString(dr["Rota"]);
                    pvoo.AeroDest = Convert.ToString(dr["AeroDest"]);
                    pvoo.DurTotVoo = Convert.ToString(dr["DurTotVoo"]);
                    pvoo.AeroAlt = Convert.ToString(dr["AeroAlt"]);
                    pvoo.AeroRes = Convert.ToString(dr["AeroRes"]);
                    pvoo.OutrosDados = Convert.ToString(dr["OutrosDados"]);
                    pvoo.Autonomia = Convert.ToString(dr["Autonomia"]);
                    pvoo.PessBordo = Convert.ToString(dr["PessBordo"]);
                    pvoo.RadEmer_U = Convert.ToBoolean(dr["RadEmer_U"]);
                    pvoo.RadEmer_V = Convert.ToBoolean(dr["RadEmer_V"]);
                    pvoo.RadEmer_E = Convert.ToBoolean(dr["RadEmer_E"]);
                    pvoo.EquipSobrev_P = Convert.ToBoolean(dr["EquipSobrev_P"]);
                    pvoo.EquipSobrev_D = Convert.ToBoolean(dr["EquipSobrev_D"]);
                    pvoo.EquipSobrev_M = Convert.ToBoolean(dr["EquipSobrev_M"]);
                    pvoo.EquipSobrev_J = Convert.ToBoolean(dr["EquipSobrev_J"]);
                    pvoo.VestSobrev_L = Convert.ToBoolean(dr["VestSobrev_L"]);
                    pvoo.VestSobrev_F = Convert.ToBoolean(dr["VestSobrev_F"]);
                    pvoo.VestSobrev_U = Convert.ToBoolean(dr["VestSobrev_U"]);

CMDBuddyFinal/Controllers/PainelController.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMDBuddyFinal.Models;
using Microsoft.Ajax.Utilities;


namespace CMDBuddyFinal.Controllers
{
    public class PainelController : Controller
    {
        // GET: Painel
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DBordo()
        {
            ViewBag.Message = "Diários de Bordo";
            return View();
        }

        public ActionResult PVoo()
        {
            ViewBag.Message = "Planos de Voo";
            return View();
        }

        public ActionResult CFerramentas()
        {
            ViewBag.Message = "Caixa de Ferramentas";
            return View();
        }

        [HttpPost]
        public ActionResult Index(Usuario usuario)
        {
            Conexao conexao = new Conexao();
            string StrQuery = "SELECT * FROM users WHERE ";
            StrQuery += "login = '" + usuario.Username + "' and ";
            StrQuery += "senha = '" + usuario.Userpass + "';";
            using (MySqlCommand comando = new MySqlCommand(StrQuery, conexao.conn))
            {
                MySqlDataReader dr = comando.ExecuteReader();
                if (dr.HasRows)
                {
                    _ = dr.Read();
                    return View();
                }
                else
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
            }
        }
    }
}

CMDBuddyFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Commander Buddy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
     <nav class="navbar navbar-dark fixed-top" style="background-color: #1A67CF; ">
        <a class="navbar-brand" href="#">CommanderBuddy</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse text-center" id="navbarsExample01" style="background-color: #005bc5">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Home", "Index", "Home")</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Sobre", "About", "Home")</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Contato", "Contact", "Home")</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Login e Cadastro", "Index", "Login")</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CMDBuddyFinal/Views/Shared/_LayoutPiloto.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CommanderBuddy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <nav class="navbar navbar-dark fixed-top" style="background-color: #1A67CF; ">
        <a class="navbar-brand" href="#">CommanderBuddy</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse text-center" id="navbarsExample01" style="background-color: #005bc5">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Painel de Controle", "Index", "Painel")</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Diarios de Bordo", "Index", "DBordo")</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Planos de Voo", "Index", "PVoo")</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" @Html.ActionLink("Caixa de Ferramentas", "Index", "CFerramentas")</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CMD ENTERPRISES</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CMDBuddyFinal/Views/Shared/_LayoutSemNavbar.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CommanderBuddy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CMD ENTERPRISES</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CMDBuddyFinal/Views/Shared/_LayoutVazio.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.5">
    <title>@ViewBag.Title - CommanderBuddy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #1A67CF; ">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                    <a class="navbar-brand" style="color: white">CommanderBuddy</a>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CMD ENTERPRISES</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>